Framework/Controllers/CountryManagmentController.cs
using Core;
using ExceptionLogging;
using FramWork.HelloService;
using FramWork.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FramWork.Controllers
{
    public class CountryManagmentController : Controller
    {

        #region Index
        // GET: CountryManagment
        [LoginAuthorize]
        public ActionResult Index()
        {
            Core.Basic.TimeLineDescription(this.ControllerContext.RouteData.Values["controller"].ToString(),
       this.ControllerContext.RouteData.Values["action"].ToString(), "The user " + Login.FirstName + " " + Login.LastName + "Entered into Country List Page");
            return View();
        }
        #endregion

        #region TableData
        [HttpGet, LoginAuthorize]
        public string TableData()
        {
            try
            {
                string search = Request.QueryString["search[value]"];
                string page = Request.QueryString["start"];
                string displaylimit = Request.QueryString["length"];
                string order = Request.QueryString["order[0][column]"];
                string orderBy = Request.QueryString["order[0][dir]"];
                int totalData = 0;
                HelloServiceClient client = new HelloService.HelloServiceClient("BasicHttpBinding_IHelloService");
                var LstCountry = client.GetCountryLst(Login.OrganizationId);

                totalData = LstCountry.Count();
                if (!string.IsNullOrEmpty(search))
                    LstCountry = LstCountry.Where(a => a.CountyName.Contains(search)).ToArray();
                if (!string.IsNullOrEmpty(order))
                {
                    switch (order)
                    {
                        case "1":
                            LstCountry = (orderBy == "asc" ? LstCountry.OrderBy(a => a.CountyName) : LstCountry.OrderByDescending(a => a.CountyName)).ToArray();
                            break;
                        case "2":
                            LstCountry = (orderBy == "asc" ? LstCountry.OrderBy(a => a.CreateDate) : LstCountry.OrderByDescending(a => a.CreateDate)).ToArray();
                            break;
                        case "3":
                            LstCountry = (orderBy == "asc" ? LstCountry.OrderBy(a => a.ModifiedDate) : LstCountry.OrderByDescending(a => a.ModifiedDate)).ToArray();
                            break;
                        case "4":
                            LstCountry = (orderBy == "asc" ? LstCountry.OrderBy(a => a.IsoCode) : LstCountry.OrderByDescending(a => a.IsoCode)).ToArray();
                            break;
                        default:
                            LstCountry = (orderBy == "asc" ? LstCountry.OrderBy(a => a.Id) : LstCountry.OrderByDescending(a => a.Id)).ToArray();
                            break;
                    }
                }
                else
                    LstCountry = LstCountry = (orderBy == "asc" ? LstCountry.OrderBy(a => a.Id) : LstCountry.OrderByDescending(a => a.Id)).ToArray();
                if (!String.IsNullOrEmpty(page) && !string.IsNullOrEmpty(displaylimit) && displaylimit != "-1")
                {
                    try
                    {
                        LstCountry = LstCountry.Skip(Convert.ToInt32(!String.IsNullOrEmpty(page) ? page : "0")).Take(Convert.ToInt32(displaylimit)).ToArray();
                    }
                    catch { }
                }


                string aa = "{";
                aa += "\"recordsTotal\": " + totalData + ", \"recordsFiltered\": " + LstCountry.Count() + ",\"data\":[";
                int temp = 0;
                foreach (var item in LstCountry)
                {
                    if (temp > 0)
                        aa += ",";
                    temp++;
                    aa += string.Format("[\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\"]",
                        item.Id, item.CountyName, item.Locale, Convert.ToDateTime(item.CreateDate).ToString("dd/MM/yyyy"), Convert.ToDateTime(item.ModifiedDate).ToString("dd/MM/yyyy"), "<a class='btn default btn-xs blue' href='" + Url.Action("Edit") + "/" + item.Id + "'><i class='fa fa-edit'></i> Edit </a><a class='btn default btn-xs black' href='" + Url.Action("Delete") + "/" + item.Id + "'><i class='fa fa-trash-o'></i> Delete </a>");
                }
                return aa + "]}";
            }
            catch (Exception ex)
            {
                #region Exception Logging
                var filename = this.GetType().Name + "_" + System.Reflection.MethodBase.GetCurrentMethod().Name + "_" + (DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Millisecond).ToString() + ".txt";
                var dir = Server.MapPath("~/Exceptions/" + (DateTime.Now.Day + "-" + DateTime.Now.Month + "-" + DateTime.Now.Year).ToString());  // folder location
                if (!Directory.Exists(dir))  // if it doesn't exist, create
                    Directory.CreateDirectory(dir);
                System.IO.File.WriteAllText(Path.Combine(dir, filename), LogHelper.CreateExceptionString(ex));
                #endregion
            }
            return "";

        }
        #endregion

        #region Create

        [LoginAuthorize]
        public ActionResult Create()
        {
            Core.Basic.TimeLineDescription(this.ControllerContext.RouteData.Values["controller"].ToString(),
       this.ControllerContext.RouteData.Values["action"].ToString(), "The user " + Login.FirstName + " " + Login.LastName + "Entered into Country Create Page");

            return View();
        }
        #endregion

        #region Add Country
        [LoginAuthorize]
        public bool AddCountry(string CountryName, string IsoCode, string IsoCurrency, string GMT, string Locale)
        {
            try
            {
                if (!String.IsNullOrEmpty(CountryName))
                {
                    FramWork.HelloService.Country tbl = new FramWork.HelloService.Country();
                    tbl.Id = Guid.NewGuid();
                    tbl.OrgId = Login.OrganizationId;
                    tbl.IsoCode = IsoCode;
                    tbl.CountyName = CountryName;
                    tbl.IsoCurrency = IsoCurrency;
                    tbl.GMT = Convert.ToInt32(GMT);
                    tbl.Locale = Locale;
                    tbl.ModifiedBy = Login.Id;
                    HelloServiceClient client = new HelloService.HelloServiceClient("BasicHttpBinding_IHelloService");
                    Core.Basic.TimeLineDescription(this.ControllerContext.RouteData.Values["controller"].ToString(),
        this.ControllerContext.RouteData.Values["action"].ToString(), "The user " + Login.FirstName + " " + Login.LastName + "Added Country");
                    client.AddCountry(tbl);
                }
                else
                {

                }
                return true;
            }
            catch (Exception ex)
            {
                #region Exception Logging
                var filename = this.GetType().Name + "_" + System.Reflection.MethodBase.GetCurrentMethod().Name + "_" + (DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Millisecond).ToString() + ".txt";
                var dir = Server.MapPath("~/Exceptions/" + (DateTime.Now.Day + "-" + DateTime.Now.Month + "-" + DateTime.Now.Year).ToString());  // folder location
                if (!Directory.Exists(dir))  // if it doesn't exist, create
                    Directory.CreateDirectory(dir);
                System.IO.File.WriteAllText(Path.Combine(dir, filename), LogHelper.CreateExceptionString(ex));
                #endregion
            }
            return false;
        }
        #endregion

        #region Get country list
        [LoginAuthorize]
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult Autocomplete(string term)
        {
            try
            {
                var result = new List<KeyValuePair<string, string>>();
                IList<SelectListItem> List = new List<SelectListItem>();
                List<RegionInfo> countries = new List<RegionInfo>();
                foreach (CultureInfo culture in CultureInfo.GetCultures(CultureTypes.SpecificCultures))
                {
                    RegionInfo country = new RegionInfo(culture.LCID);
                    if (countries.Where(p => p.Name == country.Name).Count() == 0)
                        countries.Add(country);
                }
                foreach (var item in countries)
                {
                    result.Add(new KeyValuePair<string, string>(item.TwoLetterISORegionName, item.DisplayName));
                }
                var result3 = result.Where(s => s.Value.ToLower().Contains(term.ToLower())).Select(w => w).ToList();
                return Json(result3, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                #region Exception Logging
                var filename = this.GetType().Name + "_" + System.Reflection.MethodBase.GetCurrentMethod().Name + "_" + (DateTime.Now.Hour + "_" + DateTime.Now.Minute + "_" + DateTime.Now.Millisecond).ToString() + ".txt";
                var dir = Server.MapPath("~/Exceptions/" + (DateTime.Now.Day + "-" + DateTime.Now.Month + "-" + DateTime.Now.Year).ToString());  // folder location
                if (!Directory.Exists(dir))  // if it doesn't exist, create
                    Directory.CreateDirectory(dir);
                System.IO.File.WriteAllText(Path.Combine(dir, filename), LogHelper.CreateExceptionString(ex));
                #endregion
            }

Framework/Views/CountryManagment/Index.cshtml
@using FramWork.HelloService;
@{
    ViewBag.Title = "Lead2Deal | Index Coutry";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<ul class="page-breadcrumb breadcrumb">
    <li>
        <a href="@Url.Content("~/")Home/Index">Home</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="#">Country</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="#">List</a>
    </li>
</ul>

<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption font-yellow-crusta">
            <i class="fa fa-list font-red-sunglo"></i>
            <span class="caption caption-subject bold uppercase font-red-sunglo">  Country List</span>
            <span class="caption-helper"></span>
        </div>
        <div class="actions">
            <a href="@Url.Action("Create", "CountryManagment")" class="btn blue">
                <i class="fa fa-plus"></i> Add
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="portlet box blue" id="form_wizard_1">
            <div class="portlet-title">
                <div class="caption">

                </div>
                <div class="tools hidden-xs">
                    <a href="javascript:;" class="collapse">
                    </a>
                    <a href="#portlet-config" data-toggle="modal" class="config">
                    </a>
                    <a href="javascript:;" class="reload">
                    </a>
                    <a href="javascript:;" class="remove">
                    </a>
                </div>
            </div>
            <div class="portlet-body form">

                <div class="form-wizard">
                    <div class="form-body">

                        <div class="portlet-body">
                            <table class="table table-striped table-bordered table-hover" style="min-height:0px !important;" id="CoreTable">
                                <thead>
                                    <tr>
                                        <th>SlNo</th>

                                        <th>Country</th>
                                        <th>
                                            Locale
                                        </th>
                                        <th>Created Date</th>
                                        <th>Modified Date</th>
                                        <th>Options</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

<!-- END PAGE CONTENT-->
@section Css{
    <!-- BEGIN PAGE LEVEL STYLES -->



    <link rel="stylesheet" type="text/css" href="@Url.Content("~/")assets/global/plugins/select2/select2.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/")assets/global/plugins/datatables/extensions/Scroller/css/dataTables.scroller.min.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/")assets/global/plugins/datatables/extensions/ColReorder/css/dataTables.colReorder.min.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/")assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />


    <style>
        .fileUpload {
            position: relative;
            overflow: hidden;
            margin: 10px;
        }

            .fileUpload input.upload {
                position: absolute;
                top: 0;
                right: 0;
                margin: 0;
                padding: 0;
                font-size: 20px;
                cursor: pointer;
                opacity: 0;
                filter: alpha(opacity=0);
            }

        .tabletools-dropdown-on-portlet {
            margin-top: -50px;
            margin-right:5px;
        }

        .form-control.select2-container {
            margin-left: 10px;
        }
        div.dataTables_info{
            margin-left: 10px;
        }
    </style>


}



@section Scripts{
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="@Url.Content("~")assets/global/plugins/jquery-validation/js/jquery.validate.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~")assets/global/plugins/jquery-validation/js/additional-methods.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~")assets/global/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="@Url.Content("~")assets/global/plugins/select2/select2.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script type="text/javascript" src="@Url.Content("~")assets/Programmer/Scripts/Country/formwizardcountry.js"></script>
    <script type="text/javascript" src="@Url.Content("~/")assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~/")assets/global/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~/")assets/global/plugins/datatables/extensions/ColReorder/js/dataTables.colReorder.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~/")assets/global/plugins/datatables/extensions/Scroller/js/dataTables.scroller.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~/")assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <script src="@Url.Content("~/")assets/global/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->

    <script>
        jQuery(document).ready(function () {
            FormWizard.init();

            var table = $('#CoreTable');
            $.extend(true, $.fn.DataTable.TableTools.classes, {
                "container": "btn-group tabletools-dropdown-on-portlet",
                "buttons": {
                    "normal": "btn btn-sm default",
                    "disabled": "btn btn-sm default disabled"
                },
                "collection": {
                    "container": "DTTT_dropdown dropdown-menu tabletools-dropdown-menu"
                }
            });

            var oTable = table.dataTable({


                "aoColumnDefs": [{ 'bSortable': false, 'aTargets': [0] }],
                "order": [
                    [0, 'dsc']
                ],
                "lengthMenu": [
                    [5, 15, 20, -1],
                    [5, 15, 20, "All"] // change per page values here
                ],
                "processing": true,
                "serverSide": true,
                columnDefs: [{ orderable: false, "targets": -1 }],
                "ajax": "@(Request.Url.OriginalString.ToString())/../TableData",
                // set the initial value
                "pageLength": 10,
                "dom": "<'row' <'col-md-11'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable
                "tableTools": {
                    "sSwfPath": "@Url.Content("~/")assets/global/plugins/datatables/swf/copy_csv_xls_pdf.swf",
                    aButtons: [
                           {
                               sExtends: 'collection',
                               sButtonText: 'Tools <span class="caret" />',
                               aButtons: [
                                        {
                                            "sExtends": "pdf",
                                            "sButtonText": "PDF"
                                        }, {
                                            "sExtends": "csv",
                                            "sButtonText": "CSV"
                                        }, {
                                            "sExtends": "xls",
                                            "sButtonText": "Excel"
                                        }, {
                                            "sExtends": "print",
                                            "sButtonText": "Print",
                                            "sInfo": 'Please press "CTR+P" to print or "ESC" to quit'
                                        },
                                        'select_all',
                                        'select_none'
                               ]
                           },
                    ],
                },
                "fnRowCallback": function (nRow, aData, iDisplayIndex) {
                    try {

                        $("td:first", nRow).html(iDisplayIndex + 1);
                        if (aData[4] == 'True') {
                            $("td:nth-child(5)", nRow).html("<span class=\"badge badge-primary\">ACTIVE</span>");
                        }
                        else if (aData[4] == 'False') {
                            $("td:nth-child(5)", nRow).html("<span class=\"badge badge-danger\">NOT ACTIVE</span>");
                        }
                        else {
                            $(nRow).css('background-color', 'white');
                        }
                    } catch (ex) {
                        alert("fnRowCallback exception:");
                    }
                    return nRow;
                }
            });
            var tableWrapper = $('#CoreTable_wrapper'); // datatable creates the table wrapper by adding with id {your_table_jd}_wrapper
            tableWrapper.find('.dataTables_length select').select2(); // initialize select2 dropdown


        });
    </script>
}

